name: Build APK SMKN 1 Pancur Batu

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Terima Lisensi Android SDK
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Bersihkan Karakter Tersembunyi BOM Windows (Auto-Fix)
        run: |
          find . -type f \( -name "*.xml" -o -name "*.kt" -o -name "*.kts" -o -name "*.properties" \) -exec sed -i '1s/^\xEF\xBB\xBF//' {} +

      - name: Pastikan Folder & File Audio Ada
        run: |
          mkdir -p app/src/main/res/raw
          if [ ! -f "app/src/main/res/raw/indonesia_raya.mp3" ]; then
            echo "ID3" > app/src/main/res/raw/indonesia_raya.mp3
          fi

      - name: Setup Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.4'

      - name: Compile & Build Debug APK
        run: gradle assembleDebug --no-daemon

      - name: Upload File APK Siap Download
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Otomasi_IndonesiaRaya_SMKN1_PancurBatu
          path: app/build/outputs/apk/debug/app-debug.apk